import Otriangle.MonoAnabelian.TameFrobeniusUniqueness
import Otriangle.MonoAnabelian.FixedFieldComparison
import Otriangle.MonoAnabelian.UniformizerKummerExtension
import Otriangle.MonoAnabelian.ResidueCharacteristicRank

/-!
# Rigidity of the integral Kummer comparison

For the integral monoid, Hoshi's index group is trivial.  The first ingredient is elementary:
the group of units is intrinsic to the nonzero integral monoid, and quotienting by it gives the
free monoid generated by a uniformizer.  Consequently every multiplicative automorphism of the
nonzero integral monoid preserves the normalized discrete valuation.
-/

noncomputable section

namespace Anabelian
namespace LCFT

open OTriangle ValuativeRel

universe u

/-- The chosen uniformizer, regarded as a nonzero integral element. -/
noncomputable def baseIntegerMonoidUniformizer
    (K : PointedMixedCharLocalField.{u}) : baseIntegerMonoid K :=
  ⟨uniformizerUnit K, by
    change valuation K ((uniformizerUnit K : Kˣ) : K) ≤ 1
    rw [uniformizerUnit_isUniformizer]
    exact (uniformizer_lt_one (R := K)).le⟩

/-- Units of the nonzero integral monoid are exactly valuation-ring units. -/
theorem isUnit_baseIntegerMonoid_iff
    (K : PointedMixedCharLocalField.{u}) (x : baseIntegerMonoid K) :
    IsUnit x ↔ x.1 ∈ integerUnitSubgroup K := by
  constructor
  · rintro ⟨z, rfl⟩
    let y : baseIntegerMonoid K := (z⁻¹ : (baseIntegerMonoid K)ˣ)
    have hxy : ((z : baseIntegerMonoid K).1 : Kˣ) * y.1 = 1 := by
      exact congrArg (fun w : baseIntegerMonoid K ↦ w.1) z.val_inv
    have hxle : valuation K (((z : baseIntegerMonoid K).1 : Kˣ) : K) ≤ 1 :=
      (z : baseIntegerMonoid K).property
    have hyle : valuation K ((y.1 : Kˣ) : K) ≤ 1 := y.property
    have hval : valuation K (((z : baseIntegerMonoid K).1 : Kˣ) : K) *
        valuation K ((y.1 : Kˣ) : K) = 1 := by
      have hxyK : (((z : baseIntegerMonoid K).1 : Kˣ) : K) *
          ((y.1 : Kˣ) : K) = 1 := congrArg Units.val hxy
      rw [← map_mul, hxyK, map_one]
    have honele : 1 ≤ valuation K (((z : baseIntegerMonoid K).1 : Kˣ) : K) := by
      calc
        1 = valuation K (((z : baseIntegerMonoid K).1 : Kˣ) : K) *
            valuation K ((y.1 : Kˣ) : K) := hval.symm
        _ ≤ valuation K (((z : baseIntegerMonoid K).1 : Kˣ) : K) * 1 :=
          mul_le_mul_right hyle _
        _ = valuation K (((z : baseIntegerMonoid K).1 : Kˣ) : K) := mul_one _
    apply mem_integerUnitSubgroup_of_fieldUnitValuation_eq_one K
    apply Units.ext
    exact le_antisymm hxle honele
  · intro hx
    have hxval : fieldUnitValuation K x.1 = 1 :=
      fieldUnitValuation_eq_one_of_mem_integerUnitSubgroup K x.1 hx
    let y : baseIntegerMonoid K := ⟨x.1⁻¹, by
      change valuation K (((x.1)⁻¹ : Kˣ) : K) ≤ 1
      have hxfield : valuation K (x.1 : K) = 1 := congrArg Units.val hxval
      simp only [Units.val_inv_eq_inv_val, map_inv₀, hxfield, inv_one, le_refl]⟩
    refine ⟨⟨x, y, ?_, ?_⟩, rfl⟩
    · apply Subtype.ext
      exact mul_inv_cancel x.1
    · apply Subtype.ext
      exact inv_mul_cancel x.1

/-- A valuation-ring unit has zero normalized discrete valuation. -/
theorem fieldUnitDiscreteValuation_eq_one_of_mem_integerUnitSubgroup
    (K : PointedMixedCharLocalField.{u}) (x : Kˣ)
    (hx : x ∈ integerUnitSubgroup K) :
    fieldUnitDiscreteValuation K x = 1 := by
  have hxval := fieldUnitValuation_eq_one_of_mem_integerUnitSubgroup K x hx
  change
    (((Units.mapEquiv
      (IsNonarchimedeanLocalField.valueGroupWithZeroIsoInt K).toMulEquiv).trans
      WithZero.unitsWithZeroEquiv) (fieldUnitValuation K x)) = 1
  rw [hxval, map_one]

@[simp]
theorem fieldUnitDiscreteValuation_baseIntegerMonoid_mul
    (K : PointedMixedCharLocalField.{u}) (x y : baseIntegerMonoid K) :
    fieldUnitDiscreteValuation K (x * y).1 =
      fieldUnitDiscreteValuation K x.1 * fieldUnitDiscreteValuation K y.1 :=
  map_mul (fieldUnitDiscreteValuation K) x.1 y.1

@[simp]
theorem fieldUnitDiscreteValuation_baseIntegerMonoid_pow
    (K : PointedMixedCharLocalField.{u}) (x : baseIntegerMonoid K) (n : ℕ) :
    fieldUnitDiscreteValuation K (x ^ n).1 =
      fieldUnitDiscreteValuation K x.1 ^ n :=
  map_pow (fieldUnitDiscreteValuation K) x.1 n

/-- A multiplicative equivalence of nonzero integral elements preserves the normalized discrete
valuation.  Equivalently, the induced automorphism of the quotient monoid `ℕ` is the identity. -/
theorem baseIntegerMonoidEquiv_fieldUnitDiscreteValuation
    (K : PointedMixedCharLocalField.{u})
    (e : baseIntegerMonoid K ≃* baseIntegerMonoid K)
    (x : baseIntegerMonoid K) :
    fieldUnitDiscreteValuation K (e x).1 = fieldUnitDiscreteValuation K x.1 := by
  let pi : baseIntegerMonoid K := baseIntegerMonoidUniformizer K
  obtain ⟨n, u, hu, hepi⟩ :=
    (mem_baseIntegerMonoid_iff_exists_uniformizer_pow_mul_integerUnit K (e pi).1).mp
      (e pi).property
  obtain ⟨m, v, hv, heinvpi⟩ :=
    (mem_baseIntegerMonoid_iff_exists_uniformizer_pow_mul_integerUnit K (e.symm pi).1).mp
      (e.symm pi).property
  let uM : baseIntegerMonoid K := ⟨u,
    (mem_baseIntegerMonoid_iff_exists_uniformizer_pow_mul_integerUnit K u).mpr
      ⟨0, u, hu, by simp⟩⟩
  let vM : baseIntegerMonoid K := ⟨v,
    (mem_baseIntegerMonoid_iff_exists_uniformizer_pow_mul_integerUnit K v).mpr
      ⟨0, v, hv, by simp⟩⟩
  have huM : IsUnit uM := (isUnit_baseIntegerMonoid_iff K uM).mpr hu
  have hvM : IsUnit vM := (isUnit_baseIntegerMonoid_iff K vM).mpr hv
  have he_v_unit : (e vM).1 ∈ integerUnitSubgroup K := by
    rw [← isUnit_baseIntegerMonoid_iff K]
    exact IsUnit.map e.toMonoidHom hvM
  have he_v_val : fieldUnitDiscreteValuation K (e vM).1 = 1 := by
    exact fieldUnitDiscreteValuation_eq_one_of_mem_integerUnitSubgroup K _ he_v_unit
  have hepi_sub : e pi = pi ^ n * uM := by
    apply Subtype.ext
    exact hepi
  have heinvpi_sub : e.symm pi = pi ^ m * vM := by
    apply Subtype.ext
    exact heinvpi
  have hnm : n * m = 1 := by
    have happly := congrArg e heinvpi_sub
    rw [e.apply_symm_apply, map_mul, map_pow, hepi_sub] at happly
    have hval := congrArg
      (fun z : baseIntegerMonoid K ↦ fieldUnitDiscreteValuation K z.1) happly
    simp only [fieldUnitDiscreteValuation_baseIntegerMonoid_mul,
      fieldUnitDiscreteValuation_baseIntegerMonoid_pow, he_v_val, mul_one] at hval
    have huval : fieldUnitDiscreteValuation K uM.1 = 1 := by
      exact fieldUnitDiscreteValuation_eq_one_of_mem_integerUnitSubgroup K _ hu
    rw [huval, mul_one] at hval
    have hpival : fieldUnitDiscreteValuation K pi.1 =
        Multiplicative.ofAdd (-1 : ℤ) := by
      exact fieldUnitDiscreteValuation_uniformizer K
    rw [hpival] at hval
    have hadd := congrArg Multiplicative.toAdd hval
    change (-1 : ℤ) = m * (n * (-1 : ℤ)) at hadd
    have hnmZ : (n : ℤ) * (m : ℤ) = 1 := by nlinarith
    exact_mod_cast hnmZ
  have hn : n = 1 := Nat.dvd_one.mp ⟨m, hnm.symm⟩
  have hepi_uniformizer : fieldUnitDiscreteValuation K (e pi).1 =
      fieldUnitDiscreteValuation K pi.1 := by
    rw [hepi_sub, hn]
    rw [fieldUnitDiscreteValuation_baseIntegerMonoid_mul,
      fieldUnitDiscreteValuation_baseIntegerMonoid_pow, pow_one]
    suffices fieldUnitDiscreteValuation K uM.1 = 1 by rw [this, mul_one]
    exact fieldUnitDiscreteValuation_eq_one_of_mem_integerUnitSubgroup K _ hu
  obtain ⟨r, w, hw, hx⟩ :=
    (mem_baseIntegerMonoid_iff_exists_uniformizer_pow_mul_integerUnit K x.1).mp x.property
  let wM : baseIntegerMonoid K := ⟨w,
    (mem_baseIntegerMonoid_iff_exists_uniformizer_pow_mul_integerUnit K w).mpr
      ⟨0, w, hw, by simp⟩⟩
  have hxsub : x = pi ^ r * wM := by
    apply Subtype.ext
    exact hx
  rw [hxsub, map_mul e, map_pow e,
    fieldUnitDiscreteValuation_baseIntegerMonoid_mul,
    fieldUnitDiscreteValuation_baseIntegerMonoid_pow,
    fieldUnitDiscreteValuation_baseIntegerMonoid_mul,
    fieldUnitDiscreteValuation_baseIntegerMonoid_pow, hepi_uniformizer]
  have hw_unit : IsUnit wM := (isUnit_baseIntegerMonoid_iff K wM).mpr hw
  have hew_unit : (e wM).1 ∈ integerUnitSubgroup K := by
    rw [← isUnit_baseIntegerMonoid_iff K]
    exact IsUnit.map e.toMonoidHom hw_unit
  have hwval : fieldUnitDiscreteValuation K wM.1 = 1 := by
    exact fieldUnitDiscreteValuation_eq_one_of_mem_integerUnitSubgroup K _ hw
  have hewval : fieldUnitDiscreteValuation K (e wM).1 = 1 := by
    exact fieldUnitDiscreteValuation_eq_one_of_mem_integerUnitSubgroup K _ hew_unit
  rw [hwval, hewval]

/-- A local multiplicative group has no nontrivial infinitely divisible element. -/
theorem eq_one_of_forall_exists_pow_eq
    (K : PointedMixedCharLocalField.{u}) (x : Kˣ)
    (hroot : ∀ n : ℕ, 0 < n → ∃ y : Kˣ, y ^ n = x) : x = 1 := by
  have hxfin : IsOfFinOrder x := by
    apply isOfFinOrder_of_all_residueChar_power_factorizations K x
    intro n
    obtain ⟨y, hy⟩ := hroot (K.residueChar ^ n)
      (pow_pos (Fact.out : K.residueChar.Prime).pos n)
    exact ⟨1, y, IsOfFinOrder.one, by simpa using hy.symm⟩
  let T := CommGroup.torsion Kˣ
  let C := Nat.card T
  have hC : 0 < C := Nat.card_pos
  obtain ⟨y, hy⟩ := hroot C hC
  have hyfin : IsOfFinOrder y := by
    obtain ⟨m, hm, hxm⟩ := hxfin.exists_pow_eq_one
    apply isOfFinOrder_iff_pow_eq_one.mpr
    refine ⟨C * m, Nat.mul_pos hC hm, ?_⟩
    rw [pow_mul, hy, hxm]
  let yt : T := ⟨y, hyfin⟩
  have hyt : yt ^ C = 1 := pow_card_eq_one'
  have hyC : y ^ C = 1 := congrArg Subtype.val hyt
  rw [← hy, hyC]

end LCFT

namespace OTriangle
namespace LocalGaloisGroup

open LCFT ValuativeRel

/-- Embed the nonzero integers of a finite fixed field into the nonzero integers of the common
algebraic closure. -/
noncomputable def fixedFieldBaseToIntegerMonoid
    (G : LocalGaloisGroup.{u}) (U : G.OpenSubgroupIndex) :
    LCFT.baseIntegerMonoid (G.fixedFieldPointed U) →*
      G.presentation.integerMonoid :=
  (G.fixedFieldToIntegerMonoid U).comp
    (G.fixedFieldBaseIntegerMonoidEquiv U).toMonoidHom

theorem fixedFieldBaseToIntegerMonoid_injective
    (G : LocalGaloisGroup.{u}) (U : G.OpenSubgroupIndex) :
    Function.Injective (G.fixedFieldBaseToIntegerMonoid U) :=
  (G.fixedFieldToIntegerMonoid_injective U).comp
    (G.fixedFieldBaseIntegerMonoidEquiv U).injective

/-- Recover a fixed-field integer from a global integer fixed by the corresponding open
subgroup. -/
noncomputable def fixedFieldIntegerMonoidOfFixed
    (G : LocalGaloisGroup.{u}) (U : G.OpenSubgroupIndex)
    (y : G.presentation.integerMonoid)
    (hy : ∀ σ : G.toProfiniteGrp, σ ∈ (OrderDual.ofDual U).toSubgroup →
      G.galoisElementAlgEquiv σ (((y.1 : integralClosure 𝒪[G.presentation]
        G.presentation.algebraicClosure) : G.presentation.algebraicClosure)) =
        ((y.1 : integralClosure 𝒪[G.presentation]
          G.presentation.algebraicClosure) : G.presentation.algebraicClosure)) :
    G.fixedFieldIntegerMonoid U := by
  let ya : G.presentation.algebraicClosure :=
    ((y.1 : integralClosure 𝒪[G.presentation]
      G.presentation.algebraicClosure) : G.presentation.algebraicClosure)
  have hya : ya ∈ G.fixedField U := by
    rw [IntermediateField.mem_fixedField_iff]
    exact hy
  let yl : G.fixedField U := ⟨ya, hya⟩
  have hylIntegral : IsIntegral 𝒪[G.presentation] yl := by
    apply IntermediateField.coe_isIntegral_iff.mp
    exact y.1.property
  let ylInt : integralClosure 𝒪[G.presentation] (G.fixedField U) :=
    ⟨yl, hylIntegral⟩
  have hylNe : ylInt ≠ 0 := by
    intro hzero
    apply y.property
    apply Subtype.ext
    have hz := congrArg
      (fun z : integralClosure 𝒪[G.presentation] (G.fixedField U) ↦
        (((z : G.fixedField U) : G.presentation.algebraicClosure))) hzero
    exact hz
  exact ⟨ylInt, hylNe⟩

@[simp]
theorem fixedFieldToIntegerMonoid_ofFixed
    (G : LocalGaloisGroup.{u}) (U : G.OpenSubgroupIndex)
    (y : G.presentation.integerMonoid)
    (hy : ∀ σ : G.toProfiniteGrp, σ ∈ (OrderDual.ofDual U).toSubgroup →
      G.galoisElementAlgEquiv σ (((y.1 : integralClosure 𝒪[G.presentation]
        G.presentation.algebraicClosure) : G.presentation.algebraicClosure)) =
        ((y.1 : integralClosure 𝒪[G.presentation]
          G.presentation.algebraicClosure) : G.presentation.algebraicClosure)) :
    G.fixedFieldToIntegerMonoid U (G.fixedFieldIntegerMonoidOfFixed U y hy) = y := by
  apply Subtype.ext
  apply Subtype.ext
  rfl

/-- Elements coming from a fixed field are fixed by its open subgroup. -/
theorem fixedFieldBaseToIntegerMonoid_fixed
    (G : LocalGaloisGroup.{u}) (U : G.OpenSubgroupIndex)
    (σ : G.toProfiniteGrp) (hσ : σ ∈ (OrderDual.ofDual U).toSubgroup)
    (x : LCFT.baseIntegerMonoid (G.fixedFieldPointed U)) :
    (LCFT.ReconstructedIntegralMonoid.actualAction G).smul σ
        (G.fixedFieldBaseToIntegerMonoid U x) =
      G.fixedFieldBaseToIntegerMonoid U x := by
  apply Subtype.ext
  apply Subtype.ext
  change G.galoisElementAlgEquiv σ
    ((show G.fixedField U from
      ((x.1 : (G.fixedFieldPointed U)ˣ) : G.fixedFieldPointed U)) :
        G.presentation.algebraicClosure) = _
  exact x.1.1.property ⟨σ, hσ⟩

/-- Restrict a central multiplicative automorphism of the global integral monoid, as a function
on the nonzero integers of one finite fixed field. -/
noncomputable def restrictCentralIntegerMonoid
    (G : LocalGaloisGroup.{u}) (U : G.OpenSubgroupIndex)
    (α : G.presentation.integerMonoid ≃* G.presentation.integerMonoid)
    (hα : ∀ (σ : G.toProfiniteGrp) (x : G.presentation.integerMonoid),
      α ((LCFT.ReconstructedIntegralMonoid.actualAction G).smul σ x) =
        (LCFT.ReconstructedIntegralMonoid.actualAction G).smul σ (α x)) :
    LCFT.baseIntegerMonoid (G.fixedFieldPointed U) →
      LCFT.baseIntegerMonoid (G.fixedFieldPointed U) := fun x ↦
  (G.fixedFieldBaseIntegerMonoidEquiv U).symm
    (G.fixedFieldIntegerMonoidOfFixed U
      (α (G.fixedFieldBaseToIntegerMonoid U x)) (by
        intro σ hσ
        have hfix := G.fixedFieldBaseToIntegerMonoid_fixed U σ hσ x
        have hglobal :
            (LCFT.ReconstructedIntegralMonoid.actualAction G).smul σ
              (α (G.fixedFieldBaseToIntegerMonoid U x)) =
            α (G.fixedFieldBaseToIntegerMonoid U x) := by
          rw [← hα, hfix]
        have hfield := congrArg
          (fun z : G.presentation.integerMonoid ↦
            ((z.1 : integralClosure 𝒪[G.presentation]
              G.presentation.algebraicClosure) : G.presentation.algebraicClosure)) hglobal
        change G.galoisElementAlgEquiv σ
            (((α (G.fixedFieldBaseToIntegerMonoid U x)).1 :
              integralClosure 𝒪[G.presentation]
                G.presentation.algebraicClosure) : G.presentation.algebraicClosure) = _ at hfield
        exact hfield))

@[simp]
theorem fixedFieldBaseToIntegerMonoid_restrictCentralIntegerMonoid
    (G : LocalGaloisGroup.{u}) (U : G.OpenSubgroupIndex)
    (α : G.presentation.integerMonoid ≃* G.presentation.integerMonoid)
    (hα : ∀ (σ : G.toProfiniteGrp) (x : G.presentation.integerMonoid),
      α ((LCFT.ReconstructedIntegralMonoid.actualAction G).smul σ x) =
        (LCFT.ReconstructedIntegralMonoid.actualAction G).smul σ (α x))
    (x : LCFT.baseIntegerMonoid (G.fixedFieldPointed U)) :
    G.fixedFieldBaseToIntegerMonoid U
        (G.restrictCentralIntegerMonoid U α hα x) =
      α (G.fixedFieldBaseToIntegerMonoid U x) := by
  change G.fixedFieldToIntegerMonoid U
    (G.fixedFieldBaseIntegerMonoidEquiv U
      ((G.fixedFieldBaseIntegerMonoidEquiv U).symm
        (G.fixedFieldIntegerMonoidOfFixed U
          (α (G.fixedFieldBaseToIntegerMonoid U x)) _))) = _
  rw [(G.fixedFieldBaseIntegerMonoidEquiv U).apply_symm_apply]
  exact G.fixedFieldToIntegerMonoid_ofFixed U _ _

/-- Restrict a central multiplicative automorphism of the global integral monoid to the nonzero
integers of one finite fixed field. -/
noncomputable def restrictCentralIntegerMonoidHom
    (G : LocalGaloisGroup.{u}) (U : G.OpenSubgroupIndex)
    (α : G.presentation.integerMonoid ≃* G.presentation.integerMonoid)
    (hα : ∀ (σ : G.toProfiniteGrp) (x : G.presentation.integerMonoid),
      α ((LCFT.ReconstructedIntegralMonoid.actualAction G).smul σ x) =
        (LCFT.ReconstructedIntegralMonoid.actualAction G).smul σ (α x)) :
    LCFT.baseIntegerMonoid (G.fixedFieldPointed U) →*
      LCFT.baseIntegerMonoid (G.fixedFieldPointed U) where
  toFun := G.restrictCentralIntegerMonoid U α hα
  map_one' := by
    apply G.fixedFieldBaseToIntegerMonoid_injective U
    rw [G.fixedFieldBaseToIntegerMonoid_restrictCentralIntegerMonoid,
      map_one, map_one]
  map_mul' x y := by
    apply G.fixedFieldBaseToIntegerMonoid_injective U
    rw [map_mul, G.fixedFieldBaseToIntegerMonoid_restrictCentralIntegerMonoid,
      G.fixedFieldBaseToIntegerMonoid_restrictCentralIntegerMonoid,
      G.fixedFieldBaseToIntegerMonoid_restrictCentralIntegerMonoid, map_mul, map_mul]

@[simp]
theorem fixedFieldBaseToIntegerMonoid_restrictCentralIntegerMonoidHom
    (G : LocalGaloisGroup.{u}) (U : G.OpenSubgroupIndex)
    (α : G.presentation.integerMonoid ≃* G.presentation.integerMonoid)
    (hα : ∀ (σ : G.toProfiniteGrp) (x : G.presentation.integerMonoid),
      α ((LCFT.ReconstructedIntegralMonoid.actualAction G).smul σ x) =
        (LCFT.ReconstructedIntegralMonoid.actualAction G).smul σ (α x))
    (x : LCFT.baseIntegerMonoid (G.fixedFieldPointed U)) :
    G.fixedFieldBaseToIntegerMonoid U
        (G.restrictCentralIntegerMonoidHom U α hα x) =
      α (G.fixedFieldBaseToIntegerMonoid U x) := by
  exact G.fixedFieldBaseToIntegerMonoid_restrictCentralIntegerMonoid U α hα x

/-- The restriction of a central global automorphism is an automorphism at every finite fixed
field. -/
noncomputable def restrictCentralIntegerMonoidEquiv
    (G : LocalGaloisGroup.{u}) (U : G.OpenSubgroupIndex)
    (α : G.presentation.integerMonoid ≃* G.presentation.integerMonoid)
    (hα : ∀ (σ : G.toProfiniteGrp) (x : G.presentation.integerMonoid),
      α ((LCFT.ReconstructedIntegralMonoid.actualAction G).smul σ x) =
        (LCFT.ReconstructedIntegralMonoid.actualAction G).smul σ (α x)) :
    LCFT.baseIntegerMonoid (G.fixedFieldPointed U) ≃*
      LCFT.baseIntegerMonoid (G.fixedFieldPointed U) := by
  have hαsymm : ∀ (σ : G.toProfiniteGrp) (x : G.presentation.integerMonoid),
      α.symm ((LCFT.ReconstructedIntegralMonoid.actualAction G).smul σ x) =
        (LCFT.ReconstructedIntegralMonoid.actualAction G).smul σ (α.symm x) := by
    intro σ x
    apply α.injective
    rw [α.apply_symm_apply, hα, α.apply_symm_apply]
  let f := G.restrictCentralIntegerMonoidHom U α hα
  let g := G.restrictCentralIntegerMonoidHom U α.symm hαsymm
  exact
    { toFun := f
      invFun := g
      left_inv := by
        intro x
        apply G.fixedFieldBaseToIntegerMonoid_injective U
        rw [G.fixedFieldBaseToIntegerMonoid_restrictCentralIntegerMonoidHom,
          G.fixedFieldBaseToIntegerMonoid_restrictCentralIntegerMonoidHom,
          α.symm_apply_apply]
      right_inv := by
        intro x
        apply G.fixedFieldBaseToIntegerMonoid_injective U
        rw [G.fixedFieldBaseToIntegerMonoid_restrictCentralIntegerMonoidHom,
          G.fixedFieldBaseToIntegerMonoid_restrictCentralIntegerMonoidHom,
          α.apply_symm_apply]
      map_mul' := f.map_mul }

/-- Package a nonzero element integral over the base valuation ring as a member of the global
nonzero integral monoid. -/
noncomputable def integerMonoidOfIntegral
    (G : LocalGaloisGroup.{u}) (x : G.presentation.algebraicClosure)
    (hx : IsIntegral 𝒪[G.presentation] x) (hx0 : x ≠ 0) :
    G.presentation.integerMonoid :=
  ⟨⟨x, hx⟩, by
    intro h
    apply hx0
    exact congrArg Subtype.val h⟩

@[simp]
theorem integerMonoidOfIntegral_coe
    (G : LocalGaloisGroup.{u}) (x : G.presentation.algebraicClosure)
    (hx : IsIntegral 𝒪[G.presentation] x) (hx0 : x ≠ 0) :
    (((G.integerMonoidOfIntegral x hx hx0).1 :
      integralClosure 𝒪[G.presentation] G.presentation.algebraicClosure) :
        G.presentation.algebraicClosure) = x := rfl

set_option maxHeartbeats 4000000 in
-- The fixed-field Kummer calculation expands several nested integral-closure coercions.
/-- A central automorphism of the integral monoid fixes every primitive root of unity.  The
Kummer root of a fixed-field uniformizer synchronizes the exponent on roots of unity with the
automorphism induced on the valuation monoid; the latter is already the identity. -/
theorem restrictCentralIntegerMonoid_fix_primitiveRoot
    (G : LocalGaloisGroup.{u})
    (α : G.presentation.integerMonoid ≃* G.presentation.integerMonoid)
    (hα : ∀ (σ : G.toProfiniteGrp) (x : G.presentation.integerMonoid),
      α ((LCFT.ReconstructedIntegralMonoid.actualAction G).smul σ x) =
        (LCFT.ReconstructedIntegralMonoid.actualAction G).smul σ (α x))
    (n : ℕ) (hn : 0 < n) (zeta : G.presentation.algebraicClosure)
    (hzeta : IsPrimitiveRoot zeta n) :
    α (G.integerMonoidOfIntegral zeta
        (IsIntegral.of_pow hn (by rw [hzeta.pow_eq_one]; exact isIntegral_one))
        (hzeta.ne_zero hn.ne')) =
      G.integerMonoidOfIntegral zeta
        (IsIntegral.of_pow hn (by rw [hzeta.pow_eq_one]; exact isIntegral_one))
        (hzeta.ne_zero hn.ne') := by
  let zM : G.presentation.integerMonoid :=
    G.integerMonoidOfIntegral zeta
      (IsIntegral.of_pow hn (by rw [hzeta.pow_eq_one]; exact isIntegral_one))
      (hzeta.ne_zero hn.ne')
  change α zM = zM
  by_cases hn1 : n = 1
  · have hzeta1 : zeta = 1 := by
      have := hzeta.pow_eq_one
      simpa only [hn1, pow_one] using this
    have hzM1 : zM = 1 := by
      apply Subtype.ext
      apply Subtype.ext
      exact hzeta1
    rw [hzM1, map_one]
  letI : NeZero n := ⟨hn.ne'⟩
  have hzMpow : zM ^ n = 1 := by
    apply Subtype.ext
    apply Subtype.ext
    exact hzeta.pow_eq_one
  have hαzpow :
      (((α zM).1 : integralClosure 𝒪[G.presentation]
        G.presentation.algebraicClosure) : G.presentation.algebraicClosure) ^ n = 1 := by
    have h := congrArg α hzMpow
    rw [map_pow, map_one] at h
    exact congrArg
      (fun w : G.presentation.integerMonoid ↦
        ((w.1 : integralClosure 𝒪[G.presentation]
          G.presentation.algebraicClosure) : G.presentation.algebraicClosure)) h
  obtain ⟨a, ha, hza⟩ := hzeta.eq_pow_of_pow_eq_one hαzpow
  obtain ⟨U, hzetaU⟩ := G.exists_mem_fixedField zeta
  let LP := G.fixedFieldPointed U
  let zetaL : LP := ⟨zeta, hzetaU⟩
  let piB : LCFT.baseIntegerMonoid LP := LCFT.baseIntegerMonoidUniformizer LP
  let pM : G.presentation.integerMonoid := G.fixedFieldBaseToIntegerMonoid U piB
  let pA : G.presentation.algebraicClosure :=
    ((pM.1 : integralClosure 𝒪[G.presentation]
      G.presentation.algebraicClosure) : G.presentation.algebraicClosure)
  have hpA0 : pA ≠ 0 := by
    intro h
    apply pM.property
    apply Subtype.ext
    exact h
  letI : IsAlgClosed G.presentation.algebraicClosure :=
    IsAlgClosure.isAlgClosed G.presentation
  obtain ⟨beta, hbeta⟩ := IsAlgClosed.exists_pow_nat_eq pA hn
  have hbeta0 : beta ≠ 0 := by
    intro h
    apply hpA0
    rw [← hbeta, h, zero_pow hn.ne']
  have hbetaInt : IsIntegral 𝒪[G.presentation] beta := by
    apply IsIntegral.of_pow hn
    rw [hbeta]
    exact pM.1.property
  let bM : G.presentation.integerMonoid :=
    G.integerMonoidOfIntegral beta hbetaInt hbeta0
  have hbMpow : bM ^ n = pM := by
    apply Subtype.ext
    apply Subtype.ext
    exact hbeta
  let eL := G.restrictCentralIntegerMonoidEquiv U α hα
  have hpiDisc := LCFT.baseIntegerMonoidEquiv_fieldUnitDiscreteValuation LP eL piB
  let apiB : LCFT.baseIntegerMonoid LP := eL piB
  have hapiEmbed : G.fixedFieldBaseToIntegerMonoid U apiB = α pM := by
    exact G.fixedFieldBaseToIntegerMonoid_restrictCentralIntegerMonoidHom U α hα piB
  have habpowM : (α bM) ^ n = α pM := by
    rw [← map_pow, hbMpow]
  let abeta : G.presentation.algebraicClosure :=
    (((α bM).1 : integralClosure 𝒪[G.presentation]
      G.presentation.algebraicClosure) : G.presentation.algebraicClosure)
  have habeta0 : abeta ≠ 0 := by
    intro h
    apply (α bM).property
    apply Subtype.ext
    exact h
  let cA : G.presentation.algebraicClosure := abeta / beta ^ a
  have hcA0 : cA ≠ 0 := div_ne_zero habeta0 (pow_ne_zero _ hbeta0)
  have hcAU : cA ∈ G.fixedField U := by
    rw [IntermediateField.mem_fixedField_iff]
    intro σ hσ
    let s := G.galoisElementAlgEquiv σ
    let rA : G.presentation.algebraicClosure := s beta / beta
    have hpfixM := G.fixedFieldBaseToIntegerMonoid_fixed U σ hσ piB
    have hpfix : s pA = pA := by
      exact congrArg
        (fun w : G.presentation.integerMonoid ↦
          ((w.1 : integralClosure 𝒪[G.presentation]
            G.presentation.algebraicClosure) : G.presentation.algebraicClosure)) hpfixM
    have hrA0 : rA ≠ 0 := div_ne_zero ((map_ne_zero s).mpr hbeta0) hbeta0
    have hrpow : rA ^ n = 1 := by
      dsimp only [rA]
      rw [div_pow, ← map_pow, hbeta, hpfix, div_self hpA0]
    obtain ⟨i, hi, hri⟩ := hzeta.eq_pow_of_pow_eq_one hrpow
    have hrInt : IsIntegral 𝒪[G.presentation] rA :=
      IsIntegral.of_pow hn (by rw [hrpow]; exact isIntegral_one)
    let rM : G.presentation.integerMonoid := G.integerMonoidOfIntegral rA hrInt hrA0
    have hrMz : rM = zM ^ i := by
      apply Subtype.ext
      apply Subtype.ext
      exact hri.symm
    have hsBeta : s beta = rA * beta := by
      dsimp only [rA]
      field_simp
    have hsbM : (LCFT.ReconstructedIntegralMonoid.actualAction G).smul σ bM =
        rM * bM := by
      apply Subtype.ext
      apply Subtype.ext
      exact hsBeta
    have hαr :
        (((α rM).1 : integralClosure 𝒪[G.presentation]
          G.presentation.algebraicClosure) : G.presentation.algebraicClosure) = rA ^ a := by
      rw [hrMz, map_pow]
      change
        (((α zM).1 : integralClosure 𝒪[G.presentation]
          G.presentation.algebraicClosure) : G.presentation.algebraicClosure) ^ i = rA ^ a
      rw [← hza, ← hri, ← pow_mul, ← pow_mul, Nat.mul_comm a i]
    have hsabM : (LCFT.ReconstructedIntegralMonoid.actualAction G).smul σ (α bM) =
        α rM * α bM := by
      rw [← hα, hsbM, map_mul]
    have hsabeta : s abeta = rA ^ a * abeta := by
      have hfield := congrArg
        (fun w : G.presentation.integerMonoid ↦
          ((w.1 : integralClosure 𝒪[G.presentation]
            G.presentation.algebraicClosure) : G.presentation.algebraicClosure)) hsabM
      change s abeta =
        (((α rM).1 : integralClosure 𝒪[G.presentation]
          G.presentation.algebraicClosure) : G.presentation.algebraicClosure) * abeta at hfield
      rw [hαr] at hfield
      exact hfield
    dsimp only [cA]
    change s (abeta / beta ^ a) = abeta / beta ^ a
    rw [map_div₀, hsabeta, map_pow, hsBeta, mul_pow]
    field_simp
  let cL : LP := ⟨cA, hcAU⟩
  have hcL0 : cL ≠ 0 := by
    intro h
    apply hcA0
    exact congrArg Subtype.val h
  let cU : LPˣ := Units.mk0 cL hcL0
  have heqA :
      (((α pM).1 : integralClosure 𝒪[G.presentation]
        G.presentation.algebraicClosure) : G.presentation.algebraicClosure) =
        cA ^ n * pA ^ a := by
    have habpow := congrArg
      (fun w : G.presentation.integerMonoid ↦
        ((w.1 : integralClosure 𝒪[G.presentation]
          G.presentation.algebraicClosure) : G.presentation.algebraicClosure)) habpowM
    calc
      (((α pM).1 : integralClosure 𝒪[G.presentation]
          G.presentation.algebraicClosure) : G.presentation.algebraicClosure) =
          abeta ^ n := habpow.symm
      _ = (cA * beta ^ a) ^ n := by rw [div_mul_cancel₀ abeta (pow_ne_zero _ hbeta0)]
      _ = cA ^ n * (beta ^ n) ^ a := by
        rw [mul_pow, ← pow_mul, ← pow_mul, Nat.mul_comm a n]
      _ = cA ^ n * pA ^ a := by rw [hbeta]
  have heqL : (apiB.1 : LPˣ) = cU ^ n * (piB.1 : LPˣ) ^ a := by
    apply Units.ext
    apply Subtype.ext
    have hapiA := congrArg
      (fun w : G.presentation.integerMonoid ↦
        ((w.1 : integralClosure 𝒪[G.presentation]
          G.presentation.algebraicClosure) : G.presentation.algebraicClosure)) hapiEmbed
    exact hapiA.trans heqA
  have hdisc := congrArg (LCFT.fieldUnitDiscreteValuation LP) heqL
  rw [map_mul, map_pow, map_pow, hpiDisc] at hdisc
  have hpiBDisc : LCFT.fieldUnitDiscreteValuation LP piB.1 =
      Multiplicative.ofAdd (-1 : ℤ) :=
    LCFT.fieldUnitDiscreteValuation_uniformizer LP
  rw [hpiBDisc] at hdisc
  have hadd := congrArg Multiplicative.toAdd hdisc
  change (-1 : ℤ) = n * (LCFT.fieldUnitDiscreteValuation LP cU).toAdd +
    a * (-1 : ℤ) at hadd
  have hmodZ : Int.ModEq n a 1 := by
    rw [Int.modEq_iff_dvd]
    refine ⟨-(LCFT.fieldUnitDiscreteValuation LP cU).toAdd, ?_⟩
    calc
      1 - (a : ℤ) = -(n * (LCFT.fieldUnitDiscreteValuation LP cU).toAdd) := by
        linarith
      _ = (n : ℤ) * (-(LCFT.fieldUnitDiscreteValuation LP cU).toAdd) := by ring
  have hmodN : Nat.ModEq n a 1 := by exact_mod_cast hmodZ
  have h1n : 1 < n := lt_of_le_of_ne
    (Nat.one_le_iff_ne_zero.mpr hn.ne') (Ne.symm hn1)
  change a % n = 1 % n at hmodN
  rw [Nat.mod_eq_of_lt ha, Nat.mod_eq_of_lt h1n] at hmodN
  have ha1 : a = 1 := hmodN
  apply Subtype.ext
  apply Subtype.ext
  change (((α zM).1 : integralClosure 𝒪[G.presentation]
    G.presentation.algebraicClosure) : G.presentation.algebraicClosure) = zeta
  rw [← hza, ha1, pow_one]

/-- The primitive-root calculation fixes every torsion element of the integral monoid. -/
theorem restrictCentralIntegerMonoid_fix_of_pow_eq_one
    (G : LocalGaloisGroup.{u})
    (α : G.presentation.integerMonoid ≃* G.presentation.integerMonoid)
    (hα : ∀ (σ : G.toProfiniteGrp) (x : G.presentation.integerMonoid),
      α ((LCFT.ReconstructedIntegralMonoid.actualAction G).smul σ x) =
        (LCFT.ReconstructedIntegralMonoid.actualAction G).smul σ (α x))
    (r : G.presentation.integerMonoid) (n : ℕ) (hn : 0 < n)
    (hr : (((r.1 : integralClosure 𝒪[G.presentation]
      G.presentation.algebraicClosure) : G.presentation.algebraicClosure)) ^ n = 1) :
    α r = r := by
  let rA : G.presentation.algebraicClosure :=
    ((r.1 : integralClosure 𝒪[G.presentation]
      G.presentation.algebraicClosure) : G.presentation.algebraicClosure)
  obtain ⟨m, hm, hprim⟩ := IsPrimitiveRoot.exists_pos hr hn.ne'
  have hfix := G.restrictCentralIntegerMonoid_fix_primitiveRoot
    α hα m hm rA hprim
  let rM : G.presentation.integerMonoid :=
    G.integerMonoidOfIntegral rA
      (IsIntegral.of_pow hm (by rw [hprim.pow_eq_one]; exact isIntegral_one))
      (hprim.ne_zero hm.ne')
  have hre : r = rM := by
    apply Subtype.ext
    apply Subtype.ext
    rfl
  rw [hre]
  exact hfix

set_option maxHeartbeats 4000000 in
-- The divisibility argument repeatedly unfolds the transported fixed-field action.
/-- The centralizer of the absolute Galois action on the nonzero integral monoid is trivial. -/
theorem centralIntegerMonoidEquiv_eq_refl
    (G : LocalGaloisGroup.{u})
    (α : G.presentation.integerMonoid ≃* G.presentation.integerMonoid)
    (hα : ∀ (σ : G.toProfiniteGrp) (x : G.presentation.integerMonoid),
      α ((LCFT.ReconstructedIntegralMonoid.actualAction G).smul σ x) =
        (LCFT.ReconstructedIntegralMonoid.actualAction G).smul σ (α x)) :
    α = MulEquiv.refl G.presentation.integerMonoid := by
  apply MulEquiv.ext
  intro x
  let xA : G.presentation.algebraicClosure :=
    ((x.1 : integralClosure 𝒪[G.presentation]
      G.presentation.algebraicClosure) : G.presentation.algebraicClosure)
  obtain ⟨U, hxU⟩ := G.exists_mem_fixedField xA
  have hxfix : ∀ σ : G.toProfiniteGrp,
      σ ∈ (OrderDual.ofDual U).toSubgroup →
        G.galoisElementAlgEquiv σ xA = xA := by
    rw [IntermediateField.mem_fixedField_iff] at hxU
    exact hxU
  let xF : G.fixedFieldIntegerMonoid U :=
    G.fixedFieldIntegerMonoidOfFixed U x hxfix
  let xB : LCFT.baseIntegerMonoid (G.fixedFieldPointed U) :=
    (G.fixedFieldBaseIntegerMonoidEquiv U).symm xF
  have hxEmbed : G.fixedFieldBaseToIntegerMonoid U xB = x := by
    change G.fixedFieldToIntegerMonoid U
      (G.fixedFieldBaseIntegerMonoidEquiv U
        ((G.fixedFieldBaseIntegerMonoidEquiv U).symm xF)) = x
    rw [(G.fixedFieldBaseIntegerMonoidEquiv U).apply_symm_apply]
    exact G.fixedFieldToIntegerMonoid_ofFixed U x hxfix
  let eL := G.restrictCentralIntegerMonoidEquiv U α hα
  let axB : LCFT.baseIntegerMonoid (G.fixedFieldPointed U) := eL xB
  have haxEmbed : G.fixedFieldBaseToIntegerMonoid U axB = α x := by
    rw [← hxEmbed]
    exact G.fixedFieldBaseToIntegerMonoid_restrictCentralIntegerMonoidHom U α hα xB
  let LP := G.fixedFieldPointed U
  let d : LPˣ := axB.1 * xB.1⁻¹
  have hdroot : ∀ q : ℕ, 0 < q → ∃ c : LPˣ, c ^ q = d := by
    intro q hq
    letI : IsAlgClosed G.presentation.algebraicClosure :=
      IsAlgClosure.isAlgClosed G.presentation
    obtain ⟨yA, hyA⟩ := IsAlgClosed.exists_pow_nat_eq xA hq
    have hyA0 : yA ≠ 0 := by
      intro hy0
      apply x.property
      apply Subtype.ext
      change xA = 0
      rw [← hyA, hy0, zero_pow hq.ne']
    have hyInt : IsIntegral 𝒪[G.presentation] yA := by
      apply IsIntegral.of_pow hq
      rw [hyA]
      exact x.1.property
    let yM : G.presentation.integerMonoid :=
      G.integerMonoidOfIntegral yA hyInt hyA0
    have hyPowM : yM ^ q = x := by
      apply Subtype.ext
      apply Subtype.ext
      exact hyA
    let ayA : G.presentation.algebraicClosure :=
      (((α yM).1 : integralClosure 𝒪[G.presentation]
        G.presentation.algebraicClosure) : G.presentation.algebraicClosure)
    have hayA0 : ayA ≠ 0 := by
      intro hay0
      apply (α yM).property
      apply Subtype.ext
      exact hay0
    let cA : G.presentation.algebraicClosure := ayA / yA
    have hcA0 : cA ≠ 0 := div_ne_zero hayA0 hyA0
    have hcAU : cA ∈ G.fixedField U := by
      rw [IntermediateField.mem_fixedField_iff]
      intro σ hσ
      let s := G.galoisElementAlgEquiv σ
      let rA : G.presentation.algebraicClosure := s yA / yA
      have hsxA : s xA = xA := hxfix σ hσ
      have hrA0 : rA ≠ 0 := div_ne_zero ((map_ne_zero s).mpr hyA0) hyA0
      have hrpow : rA ^ q = 1 := by
        dsimp only [rA]
        rw [div_pow, ← map_pow, hyA, hsxA, div_self]
        exact fun h ↦ x.property (Subtype.ext h)
      have hrInt : IsIntegral 𝒪[G.presentation] rA :=
        IsIntegral.of_pow hq (by rw [hrpow]; exact isIntegral_one)
      let rM : G.presentation.integerMonoid :=
        G.integerMonoidOfIntegral rA hrInt hrA0
      have hrfix : α rM = rM :=
        G.restrictCentralIntegerMonoid_fix_of_pow_eq_one α hα rM q hq hrpow
      have hsY : s yA = rA * yA := by
        dsimp only [rA]
        field_simp
      have hsyM : (LCFT.ReconstructedIntegralMonoid.actualAction G).smul σ yM =
          rM * yM := by
        apply Subtype.ext
        apply Subtype.ext
        exact hsY
      have hsayM : (LCFT.ReconstructedIntegralMonoid.actualAction G).smul σ (α yM) =
          rM * α yM := by
        calc
          _ = α ((LCFT.ReconstructedIntegralMonoid.actualAction G).smul σ yM) :=
            (hα σ yM).symm
          _ = α (rM * yM) := by rw [hsyM]
          _ = rM * α yM := by rw [map_mul, hrfix]
      have hsayA : s ayA = rA * ayA := by
        exact congrArg
          (fun w : G.presentation.integerMonoid ↦
            ((w.1 : integralClosure 𝒪[G.presentation]
              G.presentation.algebraicClosure) : G.presentation.algebraicClosure)) hsayM
      dsimp only [cA]
      change s (ayA / yA) = ayA / yA
      rw [map_div₀, hsayA, hsY]
      field_simp
    let cL : LP := ⟨cA, hcAU⟩
    have hcL0 : cL ≠ 0 := by
      intro hc0
      apply hcA0
      exact congrArg Subtype.val hc0
    let c : LPˣ := Units.mk0 cL hcL0
    refine ⟨c, ?_⟩
    apply Units.ext
    apply Subtype.ext
    have hayPowM : (α yM) ^ q = α x := by
      rw [← map_pow, hyPowM]
    have hayPowA := congrArg
      (fun w : G.presentation.integerMonoid ↦
        ((w.1 : integralClosure 𝒪[G.presentation]
          G.presentation.algebraicClosure) : G.presentation.algebraicClosure)) hayPowM
    have hxEmbedA := congrArg
      (fun w : G.presentation.integerMonoid ↦
        ((w.1 : integralClosure 𝒪[G.presentation]
          G.presentation.algebraicClosure) : G.presentation.algebraicClosure)) hxEmbed
    have haxEmbedA := congrArg
      (fun w : G.presentation.integerMonoid ↦
        ((w.1 : integralClosure 𝒪[G.presentation]
          G.presentation.algebraicClosure) : G.presentation.algebraicClosure)) haxEmbed
    change ayA ^ q =
      (((α x).1 : integralClosure 𝒪[G.presentation]
        G.presentation.algebraicClosure) : G.presentation.algebraicClosure) at hayPowA
    change
      ((show G.fixedField U from ((xB.1 : LPˣ) : LP)) :
        G.presentation.algebraicClosure) = xA at hxEmbedA
    change
      ((show G.fixedField U from ((axB.1 : LPˣ) : LP)) :
        G.presentation.algebraicClosure) =
          (((α x).1 : integralClosure 𝒪[G.presentation]
            G.presentation.algebraicClosure) : G.presentation.algebraicClosure) at haxEmbedA
    change cA ^ q =
      ((show G.fixedField U from ((axB.1 : LPˣ) : LP)) :
        G.presentation.algebraicClosure) *
        (((show G.fixedField U from ((xB.1 : LPˣ) : LP)) :
          G.presentation.algebraicClosure))⁻¹
    dsimp only [cA]
    rw [div_pow, hayPowA, hyA, ← haxEmbedA, ← hxEmbedA]
    rw [div_eq_mul_inv]
  have hd : d = 1 := LCFT.eq_one_of_forall_exists_pow_eq LP d hdroot
  have haxBUnit : axB.1 = xB.1 := mul_inv_eq_one.mp hd
  have haxB : axB = xB := by
    apply Subtype.ext
    exact haxBUnit
  change α x = x
  rw [← haxEmbed, ← hxEmbed, haxB]

end LocalGaloisGroup
end OTriangle
end Anabelian
