import Mathlib.Data.ZMod.QuotientGroup
import Mathlib.GroupTheory.SpecificGroups.Cyclic.Basic
import Mathlib.Topology.Algebra.Group.Quotient

/-!
# Power quotients of compact procyclic groups

A compact Hausdorff commutative group topologically generated by one element has quotient of
cardinality at most `n` modulo `n`th powers.  This generic topological lemma is separated from its
finite-residue-field application.
-/

open scoped Topology

noncomputable section

namespace Anabelian
namespace OTriangle
namespace TopologicalProcyclic

/-- The image of a topological generator generates the quotient by `n`th powers algebraically.
Compactness makes the power subgroup closed, and the cyclic subgroup in the quotient is finite,
so density forces it to be the whole quotient. -/
theorem quotient_zpowers_eq_top
    {A : Type*} [CommGroup A] [TopologicalSpace A] [IsTopologicalGroup A]
    [CompactSpace A] [T2Space A] (generator : A)
    (dense : (Subgroup.zpowers generator).topologicalClosure = ⊤)
    (n : ℕ) (hn : 0 < n) :
    Subgroup.zpowers
        ((QuotientGroup.mk' ((powMonoidHom (α := A) n).range)) generator) = ⊤ := by
  let H : Subgroup A := (powMonoidHom (α := A) n).range
  have hHclosed : IsClosed (H : Set A) := by
    change IsClosed (Set.range fun x : A ↦ x ^ n)
    exact (isCompact_range (continuous_pow n)).isClosed
  letI : IsClosed (H : Set A) := hHclosed
  let Q := A ⧸ H
  let q : A →* Q := QuotientGroup.mk' H
  let g : Q := q generator
  have hgpow : g ^ n = 1 := by
    change q (generator ^ n) = 1
    change ((generator ^ n : A) : A ⧸ H) = 1
    rw [QuotientGroup.eq_one_iff]
    exact ⟨generator, rfl⟩
  have hdenseGenerator : DenseRange (generator ^ · : ℤ → A) := by
    rw [DenseRange, ← Subgroup.coe_zpowers, dense_iff_closure_eq]
    have hcoe := congrArg (fun S : Subgroup A ↦ (S : Set A)) dense
    simpa only [Subgroup.topologicalClosure_coe, Subgroup.coe_top] using hcoe
  have hqDense : DenseRange q :=
    (QuotientGroup.mk'_surjective H).denseRange
  have hcomp : DenseRange (q ∘ (generator ^ · : ℤ → A)) :=
    hqDense.comp hdenseGenerator QuotientGroup.continuous_mk
  have hgDense : DenseRange (g ^ · : ℤ → Q) := by
    convert hcomp using 1
    funext z
    exact map_zpow q generator z
  have hzpDense : Dense (Subgroup.zpowers g : Set Q) := by
    simpa only [DenseRange, Subgroup.coe_zpowers] using hgDense
  have hgFinite : IsOfFinOrder g :=
    isOfFinOrder_iff_pow_eq_one.mpr ⟨n, hn, hgpow⟩
  have hzpClosed : IsClosed (Subgroup.zpowers g : Set Q) :=
    hgFinite.finite_zpowers.isClosed
  change Subgroup.zpowers g = ⊤
  rw [SetLike.ext'_iff]
  apply Set.Subset.antisymm (Set.subset_univ _)
  have hclosure := hzpDense.closure_eq
  rw [hzpClosed.closure_eq] at hclosure
  simp [hclosure]

/-- The quotient of a compact procyclic commutative group by `n`th powers is finite. -/
theorem modPower_finite
    {A : Type*} [CommGroup A] [TopologicalSpace A] [IsTopologicalGroup A]
    [CompactSpace A] [T2Space A] (generator : A)
    (dense : (Subgroup.zpowers generator).topologicalClosure = ⊤)
    (n : ℕ) (hn : 0 < n) :
    Finite (A ⧸ (powMonoidHom (α := A) n).range) := by
  let H : Subgroup A := (powMonoidHom (α := A) n).range
  let Q := A ⧸ H
  let q : A →* Q := QuotientGroup.mk' H
  let g : Q := q generator
  have hgpow : g ^ n = 1 := by
    change q (generator ^ n) = 1
    change ((generator ^ n : A) : A ⧸ H) = 1
    rw [QuotientGroup.eq_one_iff]
    exact ⟨generator, rfl⟩
  have hgFinite : IsOfFinOrder g :=
    isOfFinOrder_iff_pow_eq_one.mpr ⟨n, hn, hgpow⟩
  letI : Fintype (Subgroup.zpowers g) := hgFinite.finite_zpowers.fintype
  apply Finite.of_surjective ((↑) : Subgroup.zpowers g → Q)
  intro x
  refine ⟨⟨x, ?_⟩, rfl⟩
  have htop := quotient_zpowers_eq_top generator dense n hn
  change x ∈ Subgroup.zpowers g
  rw [htop]
  exact Subgroup.mem_top x

/-- A compact procyclic commutative group has at most `n` classes modulo `n`th powers. -/
theorem modPower_card_le
    {A : Type*} [CommGroup A] [TopologicalSpace A] [IsTopologicalGroup A]
    [CompactSpace A] [T2Space A] (generator : A)
    (dense : (Subgroup.zpowers generator).topologicalClosure = ⊤)
    (n : ℕ) (hn : 0 < n) :
    Nat.card (A ⧸ (powMonoidHom (α := A) n).range) ≤ n := by
  letI := modPower_finite generator dense n hn
  let H : Subgroup A := (powMonoidHom (α := A) n).range
  let Q := A ⧸ H
  let q : A →* Q := QuotientGroup.mk' H
  let g : Q := q generator
  have hgpow : g ^ n = 1 := by
    change q (generator ^ n) = 1
    change ((generator ^ n : A) : A ⧸ H) = 1
    rw [QuotientGroup.eq_one_iff]
    exact ⟨generator, rfl⟩
  have hzpTop : Subgroup.zpowers g = ⊤ :=
    quotient_zpowers_eq_top generator dense n hn
  rw [← orderOf_eq_card_of_zpowers_eq_top hzpTop]
  exact orderOf_le_of_pow_eq_one hn hgpow

end TopologicalProcyclic
end OTriangle
end Anabelian
