import Otriangle.MonoAnabelian.UnramifiedKummerCompositum
import Otriangle.MonoAnabelian.InertiaComparison
import Otriangle.MonoAnabelian.FiniteTameRestriction

/-!
# Faithfulness of tame conjugation

A non-inertial absolute Galois element moves an element of the residue algebraic closure.  The
finite residue field generated by that element determines an unramified layer.  A prime-to-
characteristic Teichmüller lift in this layer and a Kummer root of a base uniformizer then give a
finite tame-inertia element whose conjugation commutator detects the original residue action.
-/

noncomputable section

namespace Anabelian.OTriangle.LocalGaloisGroup

open LCFT ValuativeRel Polynomial
open FiniteTameRamification

universe u

/-- Faithfulness of the conjugation action of the classical unramified quotient on the intrinsic
tame quotient, stated without constructing the quotient action explicitly. -/
def TameConjugationFaithful
    (G : LocalGaloisGroup.{u}) (p : ℕ) : Prop :=
  ∀ g : G.toProfiniteGrp,
    (∀ x : G.toProfiniteGrp, x ∈ G.classicalInertiaSubgroup →
      g * x * g⁻¹ * x⁻¹ ∈ G.intrinsicWildInertiaSubgroup p) →
    g ∈ G.classicalInertiaSubgroup

/-- If an automorphism moves one `n`th root of unity, it moves every primitive `n`th root. -/
theorem map_ne_of_isPrimitiveRoot_of_map_ne
    {F : Type*} [Field F] (sigma : F ≃+* F) (x eta : F) (n : ℕ) [NeZero n]
    (hxpow : x ^ n = 1) (heta : IsPrimitiveRoot eta n)
    (hx : sigma x ≠ x) : sigma eta ≠ eta := by
  intro hetaFix
  obtain ⟨i, _, hxi⟩ := heta.eq_pow_of_pow_eq_one hxpow
  apply hx
  calc
    sigma x = sigma (eta ^ i) := congrArg sigma hxi.symm
    _ = (sigma eta) ^ i := map_pow sigma eta i
    _ = eta ^ i := by rw [hetaFix]
    _ = x := hxi

set_option maxHeartbeats 8000000 in
-- The proof simultaneously unfolds the residue tower, finite tame character, and two fixed fields.
/-- Tame conjugation is faithful for every presented mixed-characteristic local Galois group. -/
theorem tameConjugationFaithful_of_reciprocity
    (G : LocalGaloisGroup.{u}) (reciprocity : LocalReciprocityFamily.{u}) :
    G.TameConjugationFaithful G.presentation.residueChar := by
  intro g hcomm
  by_contra hg
  let K := G.presentation
  let k := LCFT.ResidueField K.spectralPointing
  let kbar := LCFT.AlgebraicClosureResidueField K.spectralPointing
  let phi : kbar ≃ₐ[k] kbar := K.spectralResidueGaloisMap g
  have hphi : phi ≠ 1 := by
    intro h
    apply hg
    rw [G.classicalInertiaSubgroup_eq_spectral reciprocity]
    exact h
  obtain ⟨x, hx⟩ : ∃ x : kbar, phi x ≠ x := by
    by_contra hall
    push Not at hall
    apply hphi
    apply AlgEquiv.ext
    exact hall
  have hx0 : x ≠ 0 := by
    intro hzero
    apply hx
    rw [hzero, map_zero]
  let E : G.ResidueFiniteGaloisIntermediateField :=
    FiniteGaloisIntermediateField.adjoin k {x}
  have hxE : x ∈ E.toIntermediateField :=
    FiniteGaloisIntermediateField.subset_adjoin k {x} (Set.mem_singleton x)
  letI : Finite E := Module.finite_of_finite k
  let xe : E := ⟨x, hxE⟩
  have hxe0 : xe ≠ 0 := by
    intro hzero
    apply hx0
    exact congrArg Subtype.val hzero
  let xu : Eˣ := Units.mk0 xe hxe0
  let xbaru : kbarˣ := Units.mk0 x hx0
  let n := orderOf xu
  have hn : 0 < n := orderOf_pos xu
  letI : NeZero n := ⟨hn.ne'⟩
  let U := G.residueUnramifiedOpenSubgroupOf E
  let V : G.OpenSubgroupIndex := OrderDual.toDual U
  let L := G.fixedField V
  let LP := G.fixedFieldPointed V
  let A := K.algebraicClosure
  letI := K.nontriviallyNormedField
  letI := K.isUltrametricDist
  letI := K.completeSpace
  letI := G.fixedFieldNontriviallyNormedField V
  letI := G.fixedFieldIsUltrametricDist V
  letI : ValuativeRel L := G.fixedFieldValuativeRel V
  letI : ValuativeExtension K L := G.fixedFieldValuativeExtensionFromPresentation V
  letI := G.spectralAlgebraicClosureNontriviallyNormedField
  letI := G.spectralAlgebraicClosureIsUltrametricDist
  letI : ValuativeRel A := G.spectralAlgebraicClosureValuativeRel
  letI : ValuativeExtension K A := K.spectralValuativeExtension A
  letI : ValuativeExtension L A := G.fixedFieldValuativeExtension V
  letI : IsScalarTower (IsLocalRing.ResidueField 𝒪[K])
      (IsLocalRing.ResidueField 𝒪[L]) (IsLocalRing.ResidueField 𝒪[A]) :=
    IsScalarTower.of_algebraMap_eq' (by
      apply RingHom.ext
      intro y
      obtain ⟨a, rfl⟩ := IsLocalRing.residue_surjective y
      change IsLocalRing.residue 𝒪[A] (algebraMap 𝒪[K] 𝒪[A] a) =
        algebraMap (IsLocalRing.ResidueField 𝒪[L])
          (IsLocalRing.ResidueField 𝒪[A])
            (algebraMap (IsLocalRing.ResidueField 𝒪[K])
              (IsLocalRing.ResidueField 𝒪[L])
                (IsLocalRing.residue 𝒪[K] a))
      rw [IsLocalRing.ResidueField.algebraMap_residue,
        IsLocalRing.ResidueField.algebraMap_residue]
      rfl)
  let i := G.residueUnramifiedOfResidueEmbedding E
  have hxrange : x ∈ i.fieldRange := by
    rw [G.residueUnramifiedOfResidueEmbedding_fieldRange E]
    exact hxE
  obtain ⟨b, hb⟩ := hxrange
  have hb0 : b ≠ 0 := by
    intro hzero
    apply hx0
    rw [← hb, hzero, map_zero]
  let bu : (IsLocalRing.ResidueField 𝒪[L])ˣ := Units.mk0 b hb0
  let iu : (IsLocalRing.ResidueField 𝒪[L])ˣ →* kbarˣ := Units.map i
  have hbu_map : iu bu = xbaru := by
    apply Units.ext
    exact hb
  let Esub : E →+* kbar := E.toIntermediateField.subtype
  let eu : Eˣ →* kbarˣ := Units.map Esub
  have hxu_map : eu xu = xbaru := by
    apply Units.ext
    rfl
  have hbu_order : orderOf bu = n := by
    calc
      orderOf bu = orderOf (iu bu) :=
        (orderOf_injective iu (Units.map_injective i.injective) bu).symm
      _ = orderOf xbaru := congrArg orderOf hbu_map
      _ = orderOf (eu xu) := congrArg orderOf hxu_map.symm
      _ = orderOf xu :=
        orderOf_injective eu
          (Units.map_injective (f := Esub.toMonoidHom) Esub.injective) xu
      _ = n := rfl
  obtain ⟨t, htred, htorder, hcop⟩ := LCFT.exists_integerUnit_lift_orderOf_eq LP bu
  have htorder_n : orderOf t = n := htorder.trans hbu_order
  have hcop_n : n.Coprime K.residueChar := by
    rw [← hbu_order]
    change (orderOf bu).Coprime LP.residueChar
    exact hcop
  let etaL : L := ((t.1 : LPˣ) : LP)
  have hetaL_order : orderOf etaL = n := by
    calc
      orderOf etaL = orderOf t.1 :=
        orderOf_injective (Units.coeHom L) Units.coeHom_injective t.1
      _ = orderOf t := Subgroup.orderOf_coe t
      _ = n := htorder_n
  have hetaL : IsPrimitiveRoot etaL n := IsPrimitiveRoot.iff_orderOf.mpr hetaL_order
  let hroot : (primitiveRoots n LP).Nonempty :=
    ⟨etaL, (mem_primitiveRoots hn).mpr hetaL⟩
  have hroot_primitive : IsPrimitiveRoot hroot.choose n :=
    (mem_primitiveRoots hn).mp hroot.choose_spec
  let pi : LocalIntegerRing K := localUniformizerInteger K
  have hpi : Ideal.span {pi} = localMaximalIdeal K :=
    localMaximalIdeal_eq_span_uniformizer K |>.symm
  let T := G.unramifiedKummerOpenSubgroup E pi hpi n hn
  let W : G.OpenSubgroupIndex := OrderDual.toDual T
  let M := G.fixedField W
  let MP := G.fixedFieldPointed W
  let EKM := G.fixedFieldBaseExtension W
  let ELM := G.fixedFieldFiniteExtension
    (G.residueUnramifiedIndex_le_unramifiedKummerIndex E pi hpi n hn)
  letI := G.fixedFieldNontriviallyNormedField W
  letI := G.fixedFieldIsUltrametricDist W
  letI : ValuativeRel M := G.fixedFieldValuativeRel W
  letI : TopologicalSpace M := G.fixedFieldTopologicalSpace W
  letI : IsNonarchimedeanLocalField M := G.fixedFieldIsNonarchimedeanLocalField W
  letI : Algebra K M := EKM.algebra
  letI : ValuativeExtension K M := EKM.valuativeExtension
  letI : FiniteDimensional K M := EKM.finiteDimensional
  letI : Algebra L M := ELM.algebra
  letI : ValuativeExtension L M := ELM.valuativeExtension
  letI : FiniteDimensional L M := ELM.finiteDimensional
  letI : IsScalarTower K L M := IsScalarTower.of_algebraMap_eq' rfl
  letI : IsGalois K M := G.fixedField_isGalois_of_normal T
    (G.unramifiedKummerOpenSubgroup_normal E pi hpi n hn)
  letI : IsScalarTower K K M := IsScalarTower.of_algebraMap_eq' rfl
  letI : MulSemiringAction (M ≃ₐ[K] M) 𝒪[M] :=
    SpectralLocalField.integerMulSemiringAction K K M
  letI : CharP (IsLocalRing.ResidueField 𝒪[M]) K.residueChar :=
    charP_of_injective_algebraMap
      (algebraMap (IsLocalRing.ResidueField 𝒪[K])
        (IsLocalRing.ResidueField 𝒪[M])).injective K.residueChar
  have hrootM_primitive : IsPrimitiveRoot (algebraMap L M hroot.choose) n :=
    hroot_primitive.map_of_injective (algebraMap L M).injective
  letI : Algebra M A := MP.algebra
  letI : ValuativeExtension M A := G.fixedFieldValuativeExtension W
  letI : IsScalarTower K M A := IsScalarTower.of_algebraMap_eq' (by
    apply RingHom.ext
    intro y
    change algebraMap K A y =
      @algebraMap (G.fixedField W) (G.fixedFieldPointed W).algebraicClosure
        _ _ (G.fixedFieldPointed W).algebra
        (algebraMap K (G.fixedField W) y)
    rw [G.fixedFieldPointed_algebraMap_apply]
    exact (IntermediateField.coe_algebraMap_apply (G.fixedField W) y).symm)
  letI : IsScalarTower (IsLocalRing.ResidueField 𝒪[K])
      (IsLocalRing.ResidueField 𝒪[M]) (IsLocalRing.ResidueField 𝒪[A]) :=
    IsScalarTower.of_algebraMap_eq' (by
      apply RingHom.ext
      intro y
      obtain ⟨a, rfl⟩ := IsLocalRing.residue_surjective y
      change IsLocalRing.residue 𝒪[A] (algebraMap 𝒪[K] 𝒪[A] a) =
        algebraMap (IsLocalRing.ResidueField 𝒪[M])
          (IsLocalRing.ResidueField 𝒪[A])
            (algebraMap (IsLocalRing.ResidueField 𝒪[K])
              (IsLocalRing.ResidueField 𝒪[M])
                (IsLocalRing.residue 𝒪[K] a))
      rw [IsLocalRing.ResidueField.algebraMap_residue,
        IsLocalRing.ResidueField.algebraMap_residue]
      rfl)
  obtain ⟨tau, zeta, hzeta, hchi⟩ :=
    G.exists_unramifiedKummerInertiaGenerator_tameCharacter
      E pi hpi n hn hroot
  have hTnormal : T.toSubgroup.Normal :=
    G.unramifiedKummerOpenSubgroup_normal E pi hpi n hn
  let r : G.toProfiniteGrp →* (M ≃ₐ[K] M) :=
    G.fixedFieldRestrictNormalHom T hTnormal
  let s : M ≃ₐ[K] M := r g
  let zbar : (IsLocalRing.ResidueField 𝒪[M])ˣ :=
    Units.map (IsLocalRing.residue 𝒪[M]).toMonoidHom zeta
  let zetaM : Mˣ :=
    Units.map (valuation M).integer.subtype.toMonoidHom zeta
  have hzeta_order : orderOf zeta = n := by
    calc
      orderOf zeta = orderOf zetaM := (orderOf_injective
        (Units.map (valuation M).integer.subtype.toMonoidHom)
        (Units.map_injective
          (f := (valuation M).integer.subtype.toMonoidHom)
          Subtype.coe_injective) zeta).symm
      _ = orderOf (zetaM : M) :=
        (orderOf_injective (Units.coeHom M) Units.coeHom_injective zetaM).symm
      _ = orderOf (algebraMap L M hroot.choose) := by
        rw [show (zetaM : M) = (zeta : M) by rfl, hzeta]
      _ = n := IsPrimitiveRoot.iff_orderOf.mp hrootM_primitive
  have hzbar_order : orderOf zbar = n :=
    LCFT.orderOf_unitsMap_residue_eq_of_coprime
      𝒪[M] K.residueChar n zeta hn hzeta_order hcop_n
  have hzbar_primitive : IsPrimitiveRoot (zbar : IsLocalRing.ResidueField 𝒪[M]) n := by
    rw [IsPrimitiveRoot.iff_orderOf]
    calc
      orderOf (zbar : IsLocalRing.ResidueField 𝒪[M]) = orderOf zbar :=
        orderOf_injective (Units.coeHom _) Units.coeHom_injective zbar
      _ = n := hzbar_order
  let j : IsLocalRing.ResidueField 𝒪[M] →ₐ[IsLocalRing.ResidueField 𝒪[K]]
      IsLocalRing.ResidueField 𝒪[A] := IsScalarTower.toAlgHom _ _ _
  have hj_primitive : IsPrimitiveRoot (j (zbar : IsLocalRing.ResidueField 𝒪[M])) n :=
    hzbar_primitive.map_of_injective j.injective
  have hxpow : x ^ n = 1 := by
    have hxu : xu ^ n = 1 := by
      rw [← orderOf_dvd_iff_pow_eq_one]
    have hmap := congrArg eu hxu
    rw [map_pow, hxu_map, map_one] at hmap
    exact congrArg Units.val hmap
  have hjmove : phi (j (zbar : IsLocalRing.ResidueField 𝒪[M])) ≠
      j (zbar : IsLocalRing.ResidueField 𝒪[M]) :=
    map_ne_of_isPrimitiveRoot_of_map_ne phi.toRingEquiv x
      (j (zbar : IsLocalRing.ResidueField 𝒪[M])) n hxpow hj_primitive hx
  have hcompat : j (residueAction 𝒪[M] (M ≃ₐ[K] M) s
      (zbar : IsLocalRing.ResidueField 𝒪[M])) =
      phi (j (zbar : IsLocalRing.ResidueField 𝒪[M])) := by
    change algebraMap (IsLocalRing.ResidueField 𝒪[M])
        (IsLocalRing.ResidueField 𝒪[A])
          (IsLocalRing.residue 𝒪[M] (s • (zeta : 𝒪[M]))) =
      phi (algebraMap (IsLocalRing.ResidueField 𝒪[M])
        (IsLocalRing.ResidueField 𝒪[A])
          (IsLocalRing.residue 𝒪[M] (zeta : 𝒪[M])))
    rw [IsLocalRing.ResidueField.algebraMap_residue,
      IsLocalRing.ResidueField.algebraMap_residue]
    change IsLocalRing.residue 𝒪[A]
        (algebraMap 𝒪[M] 𝒪[A] (s • (zeta : 𝒪[M]))) =
      IsLocalRing.residue 𝒪[A]
        (K.spectralClosureIntegerAlgEquiv g
          (algebraMap 𝒪[M] 𝒪[A] (zeta : 𝒪[M])))
    congr 1
    apply Subtype.ext
    exact AlgEquiv.restrictNormal_commutes g M ((zeta : 𝒪[M]) : M)
  have hresmove : residueAction 𝒪[M] (M ≃ₐ[K] M) s
      (zbar : IsLocalRing.ResidueField 𝒪[M]) ≠ zbar := by
    intro hfix
    apply hjmove
    rw [← hcompat, hfix]
  have hunitmove : Units.map (residueAction 𝒪[M] (M ≃ₐ[K] M) s) zbar ≠ zbar := by
    intro hfix
    apply hresmove
    exact congrArg Units.val hfix
  let tauConj := conjugate 𝒪[M] (M ≃ₐ[K] M) s tau
  have hfinite_ne : s * tau.1 * s⁻¹ * tau.1⁻¹ ≠ 1 := by
    intro hone
    have hsub : tauConj * tau⁻¹ = 1 := by
      apply Subtype.ext
      exact hone
    have hchar := congrArg (tameCharacter 𝒪[M] (M ≃ₐ[K] M)) hsub
    rw [map_mul, map_inv, map_one, tameCharacter_conjugate, hchi] at hchar
    apply hunitmove
    exact (mul_inv_eq_one.mp hchar)
  let I : Subgroup (M ≃ₐ[K] M) :=
    (IsLocalRing.maximalIdeal 𝒪[M]).inertia (M ≃ₐ[K] M)
  have hmapI : G.spectralInertiaSubgroup.map
      (AlgEquiv.restrictNormalHom M) = I :=
    G.map_spectralInertiaSubgroup_restrictNormalHom T
      (G.unramifiedKummerOpenSubgroup_normal E pi hpi n hn)
  have htauImage : tau.1 ∈ G.spectralInertiaSubgroup.map
      (AlgEquiv.restrictNormalHom M) := by
    rw [hmapI]
    exact tau.property
  obtain ⟨rho : G.toProfiniteGrp, hrho, hrho_tau⟩ := htauImage
  have hrho_tau' : r rho = tau.1 := hrho_tau
  have hrhoClassical : rho ∈ G.classicalInertiaSubgroup := by
    rw [G.classicalInertiaSubgroup_eq_spectral reciprocity]
    exact hrho
  have hwild : g * rho * g⁻¹ * rho⁻¹ ∈ G.intrinsicWildInertiaSubgroup K.residueChar :=
    hcomm rho hrhoClassical
  have hTneighbor : IntrinsicRamification.IsWildInertiaNeighborhood
      G.toProfiniteGrp K.residueChar T :=
    (G.isWildInertiaNeighborhood_iff_relativeRamificationIndex_coprime
      reciprocity T).mpr ⟨G.unramifiedKummerOpenSubgroup_normal E pi hpi n hn,
        (G.unramifiedKummer_relativeRamificationIndex_eq E pi hpi n hn hroot) ▸ hcop_n⟩
  have hmemT : g * rho * g⁻¹ * rho⁻¹ ∈ T :=
    (IntrinsicRamification.mem_wildInertiaSubgroup_iff
      G.toProfiniteGrp K.residueChar _).mp hwild T hTneighbor
  have hrestrict_one : r (g * rho * g⁻¹ * rho⁻¹) = 1 := by
    rw [← MonoidHom.mem_ker]
    have hrker : r.ker = T.toSubgroup := by
      dsimp only [r]
      exact G.fixedFieldRestrictNormalHom_ker T hTnormal
    rw [hrker]
    exact hmemT
  apply hfinite_ne
  simpa only [s, map_mul, map_inv, hrho_tau'] using hrestrict_one

end Anabelian.OTriangle.LocalGaloisGroup
